### ISSUE TITLE
金龙飞升bug

### ISSUE THREAD

**Issue by Pr0pHesyer** [BlueDeer233/image_generator#1]
log：
`[2022-05-05 14:51:24,159 生草图片生成器] ERROR: <class 'AttributeError'> occured when gen_jl handling message 1828535262.
[2022-05-05 14:51:24,160 生草图片生成器] ERROR: 'NoneType' object has no attribute 'groups'
Traceback (most recent call last):
  File "/home/pca/HoshinoBot/hoshino/msghandler.py", line 28, in handle_message
    await service_func.func(bot, event)
  File "/home/pca/HoshinoBot/hoshino/modules/image_generator/image_generator.py", line 100, in gen_jl
    else: url = await get_jl(args[0], args[1], args[2], args[3])
  File "/home/pca/HoshinoBot/hoshino/modules/image_generator/src/image.py", line 71, in get_jl
    return re.match(regex, t).groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'`

**Comment by BlueDeer233** [comment]
已修复
